@table =appuser

@id = 1
@body = {"with":["account, "role"]} 

GET http://blog-api.loc/init
###

GET http://blog-api.loc/{{table}}
###

GET http://blog-api.loc/{{table}}/{{id}}
###


POST http://blog-api.loc/{{table}}/0
Content-Type: application/json

{{body}}
###

PUT http://blog-api.loc/{{table}}/{{id}}
Content-Type: application/json

{{body}}
###

PATCH http://blog-api.loc/{{table}}/{{id}}
###

DELETE http://blog-api.loc/{{table}}/{{id}}
